<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Initiating CreateNewUser API.]]>
    </line>
    <line>
      <![CDATA[Verifying API response.]]>
    </line>
    <line>
      <![CDATA[Validate new user details are saved successfully.]]>
    </line>
  </reporter-output>
  <suite started-at="2024-09-14T15:30:03 EET" name="Default Suite" finished-at="2024-09-14T15:30:05 EET" duration-ms="2241">
    <groups>
    </groups>
    <test started-at="2024-09-14T15:30:03 EET" name="Foodics" finished-at="2024-09-14T15:30:05 EET" duration-ms="2241">
      <class name="SmokeTests.APIs">
        <test-method signature="TC1_Ensure_User_IsCreated_Successfully()[pri:1, instance:SmokeTests.APIs@4c762604]" started-at="2024-09-14T15:30:03 EET" name="TC1_Ensure_User_IsCreated_Successfully" finished-at="2024-09-14T15:30:05 EET" duration-ms="2135" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Avatar is not correct. expected [profile.avatar] but found [https://reqres.in/img/faces/1-image.jpg]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Avatar is not correct. expected [profile.avatar] but found [https://reqres.in/img/faces/1-image.jpg]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at SmokeTests.APIs.TC1_Ensure_User_IsCreated_Successfully(APIs.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Initiating CreateNewUser API.]]>
            </line>
            <line>
              <![CDATA[Verifying API response.]]>
            </line>
            <line>
              <![CDATA[Validate new user details are saved successfully.]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC1_Ensure_User_IsCreated_Successfully -->
      </class> <!-- SmokeTests.APIs -->
    </test> <!-- Foodics -->
  </suite> <!-- Default Suite -->
</testng-results>
